apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostname
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
      - name: hostname
        image: quay.io/songleo/hostname
        env:
        - name: VERSION
          value: "v1.0"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  selector:
    app: hostname
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  host: hostname-default.apps.demo-aws-495-hdgv2.demo.red-chesterfield.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hostname
    weight: 100
  wildcardPolicy: None
