kind: Secret
apiVersion: v1
metadata:
  name: pull-secret
  annotations:
    avp.kubernetes.io/path: "/cred/data/pullsecret"
stringData:
  .dockerconfigjson: <secret>
type: kubernetes.io/dockerconfigjson
