apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-to-github
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-to-github
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-to-github
    spec:
      containers:
      - name: alertmanager-to-github
        image: quay.io/ocm-observability/alertmanager-to-github:latest
        imagePullPolicy: Always
        env:
        - name: METRIC_CONFIG
          value: /conf/config.yml
        - name: ATG_LISTEN
          value: ':8080'
        - name: ATG_GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: alertmanager-to-github
              key: ATG_GITHUB_TOKEN
        volumeMounts:
        - name: config
          mountPath: /conf/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: alertmanager-to-github
