apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-observability

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml

configMapGenerator:
  - name: alertmanager-to-github
    files:
    - alert-blocklist.yaml
generatorOptions:
  disableNameSuffixHash: true
