apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hostname
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: soli-mc
        url: https://api.demo-aws-495-glxjk.demo.red-chesterfield.com:6443
  template:
    metadata:
      name: '{{cluster}}-hostname'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/songleo/argocd-demo.git
        targetRevision: HEAD
        path: hostname-no-route
      destination:
        server: '{{url}}'
        namespace: hostname
