apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ignore-files
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ignore-files
    repoURL: 'https://github.com/songleo/argocd-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: 'svc.yaml'
  project: default
  syncPolicy:
    automated: {}
